baseURL = "https://deadlineastrologyblog.github.io/"
languageCode = "en-us"
title = "Deadline Astrology Blog"
theme = "deadline-mystic"
paginate = 10

[params]
  mainColor = "#5319a3"
  accentColor = "#b2d6ff"
  author = "Saint Nicky JK"

[permalinks]
  posts = "/:year/:month/:day/:slug/"
